# Ejercicio 3. Operaciones con dos arrays

Primero se van a crear los dos arrays

In [1]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,9,6])
b = np.array([7,1,10,2,7,4,9,4,9,8])
print("El array a es ",a)
print("El array b es ",b)

El array a es  [1 2 3 2 3 4 3 4 9 6]
El array b es  [ 7  1 10  2  7  4  9  4  9  8]


Se calcula los elementos comunes a los dos

In [2]:
c=np.intersect1d(a,b)
print(c)

[1 2 4 9]


Se crea una array con los elementos de b que  no están  en a

In [3]:
d=np.setdiff1d(b,a)
print(d)

[ 7  8 10]


Se obtienen las posiciones en las que los elementos de ambos  arrays tienen el mismo valor. 

In [4]:
e=np.where(a == b)
print(e)

(array([3, 5, 7, 8], dtype=int64),)
