# Ejercicio 4. Algebra lineal con linalg de Scipy

1. Dada una matriz calcular su inversa.

In [1]:
from scipy import linalg
import numpy as np
#se define una matriz cuadrada
A=np.array([[1,2],[2,4]])

Para el cálculo de la inversa de A se utiliza la función inv  de la biblioteca linalg

In [2]:
inv_A=linalg.inv(A)
print ("La inversa de A es :",inv_A)

LinAlgError: singular matrix

Se observa  que se ha  producido un error porque la matriz es singular, es decir , tiene determinante 0. Se puede capturar el error.

In [3]:
print(linalg.det(A))

0.0


In [4]:
try:
    inv_A=linalg.inv(A)
except linalg.LinAlgError as e:
    print (str(e))
    
B=np.array([[1,1,2],[0,1,-4],[0,0,-1]])
print(linalg.inv(B))


singular matrix
[[ 1. -1.  6.]
 [ 0.  1. -4.]
 [ 0.  0. -1.]]


2. Se define ahora una matriz cuadrada 3x3, y se calcula su determinante
Observe el uso del operador ternario condicional de Python

In [5]:
B=np.array([[1,1,2],[0,1,-4],[0,0,-1]])
det_B=linalg.det(B)

print(" El determinante de B es:")

print(det_B)

inv_B=linalg.inv(B) if det_B!=0 else []

print("La inversa  de B es ")
print(inv_B)

 El determinante de B es:
-1.0
La inversa  de B es 
[[ 1. -1.  6.]
 [ 0.  1. -4.]
 [ 0.  0. -1.]]


3. Se calculan  los autovalores y autovectores de la matriz

In [7]:
autovalores_B,autovectores_B=linalg.eig(B)
print("Los autovalores de B son: ")
print(autovalores_B)
print("Los autovectores de B son: ")
print(autovectores_B)

Los autovalores de B son: 
[ 1.+0.j  1.+0.j -1.+0.j]
Los autovectores de B son: 
[[ 1.00000000e+00 -1.00000000e+00 -6.66666667e-01]
 [ 0.00000000e+00  2.22044605e-16  6.66666667e-01]
 [ 0.00000000e+00  0.00000000e+00  3.33333333e-01]]


4. Dado un sistema de ecuaciones lineales, resolverlo de dos formas: usando su inversa y usando la función solve() de linalg. El sistema es
                    3x+2y+z=1
                    5x+3y+4z=2
                    x+y-z=1

El resultado que se debe obtener es x=-4, y=6 y  z=1


En este caso se va  a usar otra firma de crear matrices co la función mat de Numpy

In [8]:
A = np.mat('[3 2 1;5 3 4;1, 1, -1]') 
print(A)

b = np.mat('[1;2;1]]')
print(b)
# Usando la matriz inversa
inv_A=linalg.inv(A)

solucion=inv_A * b
print("La solución con la inversa es:")
print(solucion)

# Lo mismo, usando la funcion linalg.solve(A,b)
solucion=linalg.solve(A,b)
print("La solución con solve es:")
print (solucion)

[[ 3  2  1]
 [ 5  3  4]
 [ 1  1 -1]]
[[1]
 [2]
 [1]]
La solución con la inversa es:
[[-4.]
 [ 6.]
 [ 1.]]
La solución con solve es:
[[-4.]
 [ 6.]
 [ 1.]]
